const productData = [
  {
    id: "01",
    name: "Soft Shell-R",
    category: "Outerwear",
    price: "Rp 12.900.000",
    image: "https://i.pinimg.com/1200x/dc/5e/2b/dc5e2b43fa4d953142b9145bbb67ceab.jpg",
    description: "A technical soft shell jacket engineered for urban exploration. Features a water-resistant membrane with bonded seams, articulated sleeves for unrestricted movement, and a streamlined silhouette that transitions seamlessly from trail to city.",
    material: "Polyester-elastane soft shell with water-resistant membrane",
    materialDetail: "92% Polyester, 8% Elastane | Water Column: 10,000mm | Breathability: 8,000g/m²/24h",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Grey", "Navy"],
    weight: "580g",
    care: "Machine wash cold, do not tumble dry, do not iron",
    season: "SS26",
  },
  {
    id: "02",
    name: "Nylon Metal Jacket",
    category: "Jackets",
    price: "Rp 15.400.000",
    image: "https://i.pinimg.com/1200x/d8/ca/88/d8ca88b05111fffedf9402ebd5f9ec2a.jpg",
    description: "Iconic nylon metal jacket with the signature iridescent weave that shifts color under light. Lined with a lightweight mesh for breathability, featuring multiple utility pockets and adjustable cuffs. A statement piece built with innovation at its core.",
    material: "Nylon Metal — iridescent nylon ripstop",
    materialDetail: "100% Nylon | Garment dyed | Water repellent finish | Signature Stone Island compass badge",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Graphite", "Dark Ice", "Green"],
    weight: "520g",
    care: "Machine wash 30°C, do not bleach, do not tumble dry",
    season: "SS26",
  },
  {
    id: "03",
    name: "Ghost Piece Overshirt",
    category: "Overshirt",
    price: "Rp 9.750.000",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz6h_1Jyoxci49RxKFtTHwGtynN7JEEnmUuedXnnFAOI0BwFibnqc7SmlV&s=10",
    description: "Part of the Ghost Piece family — tonal from top to bottom, including zippers, buttons, and badge. Made from a compact cotton-nylon weave that provides structure without bulk. Designed as a layering piece or lightweight outer layer.",
    material: "Cotton-nylon compact weave",
    materialDetail: "70% Cotton, 30% Nylon | Garment dyed | Tonal hardware | Ghost compass badge",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ghost White", "Ghost Black"],
    weight: "450g",
    care: "Machine wash cold, hang dry recommended",
    season: "AW25",
  },
  {
    id: "04",
    name: "Compass Hoodie",
    category: "Sweatshirts",
    price: "Rp 5.200.000",
    image: "https://i.pinimg.com/1200x/b1/2f/0d/b12f0df5424556f6f197ac494cd6485f.jpg",
    description: "Premium heavyweight hoodie featuring the iconic Stone Island compass logo embroidered on the chest. Made from brushed-back cotton fleece for exceptional warmth and comfort. Ribbed cuffs and hem ensure a secure fit.",
    material: "Brushed-back cotton fleece",
    materialDetail: "100% Cotton | 400gsm heavyweight | Brushed interior | Embroidered compass logo",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "White", "Grey Melange"],
    weight: "650g",
    care: "Machine wash 30°C, do not bleach, tumble dry low",
    season: "SS26",
  },
  {
    id: "05",
    name: "Cargo Pants",
    category: "Trousers",
    price: "Rp 6.400.000",
    image: "https://i.pinimg.com/1200x/60/5f/0f/605f0fc8d7f798c4d5a4d6f947a5328b.jpg",
    description: "Technical cargo trousers with a relaxed fit and multiple utility pockets. Constructed from durable ripstop nylon with a water-repellent finish. Articulated knees and adjustable ankle cuffs provide functionality for any environment.",
    material: "Nylon ripstop with water-repellent coating",
    materialDetail: "100% Nylon ripstop | DWR finish | 6 pockets | Articulated knees",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Khaki", "Navy"],
    weight: "420g",
    care: "Machine wash cold, do not iron decoration",
    season: "SS26",
  },
  {
    id: "06",
    name: "Technical Vest",
    category: "Outerwear",
    price: "Rp 8.900.000",
    image: "https://i.pinimg.com/1200x/ed/86/da/ed86da85324bae435bd82a50ece8863a.jpg",
    description: "A lightweight technical vest designed for layering. Features a quilted construction with synthetic insulation for warmth without bulk. Zip-front closure with chin guard and multiple zip pockets for secure storage.",
    material: "Quilted nylon with synthetic insulation",
    materialDetail: "100% Nylon shell | Recycled polyester insulation | Lightweight quilting | YKK zippers",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Olive"],
    weight: "380g",
    care: "Machine wash cold, do not dry clean",
    season: "AW25",
  },
  {
    id: "07",
    name: "Organic Cotton Jersey",
    category: "T-Shirts",
    price: "Rp 2.850.000",
    image: "https://stoneisland-cdn.thron.com/delivery/public/image/stoneisland/L2S152100007S0500V0001_F/ppk73x/std/768x1024/2100007-organic-cotton-jersey,-photo.jpg?scalemode=centered&adjustcrop=reduce&quality=90&format=avif",
    description: "Essential organic cotton jersey with a regular fit and clean finish. Made from certified organic cotton that is soft, breathable, and sustainably produced. Features a subtle Stone Island badge on the sleeve.",
    material: "Certified organic cotton jersey",
    materialDetail: "100% Organic Cotton | 200gsm | GOTS certified | Enzyme washed for softness",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Navy", "Grey"],
    weight: "220g",
    care: "Machine wash 30°C, do not bleach, iron low",
    season: "SS26",
  },
  {
    id: "08",
    name: "Garment Dyed Jacket",
    category: "Jackets",
    price: "Rp 11.300.000",
    image: "https://i.pinimg.com/1200x/ba/cd/84/bacd849d6a830e4ec8598862bc673e51.jpg",
    description: "Classic garment-dyed jacket with a rich, saturated color achieved through Stone Island's proprietary dyeing process. Each piece is unique due to the garment-dye technique. Features multiple pockets and adjustable drawstring hem.",
    material: "Garment-dyed cotton gabardine",
    materialDetail: "100% Cotton | Garment dyed | Water repellent | Tonal button closure",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Moss Green", "Dark Brown", "Indigo"],
    weight: "680g",
    care: "Machine wash 30°C separately, do not bleach",
    season: "AW25",
  },
  {
    id: "09",
    name: "Technical Overshirt",
    category: "Overshirt",
    price: "Rp 10.200.000",
    image: "https://www.zoofashions.com/cdn/shop/files/Stone-Island-Blue-Canvas-Weave-Overshirt-K2S151200004-V0020-1.jpg?v=1753465866&width=1200",
    description: "A technical overshirt crafted from a dense canvas weave with a crisp hand feel. Designed with a boxy fit, chest flap pockets, and a stand collar. Works as a lightweight jacket or a layering piece over knitwear.",
    material: "Dense canvas weave cotton-nylon",
    materialDetail: "65% Cotton, 35% Nylon | Canvas weave | Button closure | Chest flap pockets",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black", "Sand"],
    weight: "520g",
    care: "Machine wash cold, hang dry",
    season: "SS26",
  },
  {
    id: "10",
    name: "Lightweight Parka",
    category: "Outerwear",
    price: "Rp 13.800.000",
    image: "https://i.pinimg.com/1200x/9c/5b/74/9c5b74b4f85422cdf7e0414f11a47c2c.jpg",
    description: "A lightweight parka designed for transitional weather. Features a water-resistant shell with a removable hood, storm flap, and multiple internal pockets. The clean silhouette makes it versatile for both casual and technical styling.",
    material: "Lightweight water-resistant nylon",
    materialDetail: "100% Nylon | Water resistant | Removable hood | Mesh lined | Snap and zip closure",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Navy", "Olive"],
    weight: "620g",
    care: "Machine wash cold, do not tumble dry",
    season: "AW25",
  },
  {
    id: "11",
    name: "Utility Shirt",
    category: "Shirts",
    price: "Rp 4.900.000",
    image: "https://i.pinimg.com/736x/62/63/01/626301c930dd7c7a4001bbab9250a9d1.jpg",
    description: "A rugged utility shirt made from heavy cotton twill with a lived-in feel. Features dual chest pockets with button flaps, a relaxed fit, and reinforced seams for durability. An everyday essential with workwear-inspired details.",
    material: "Heavy cotton twill",
    materialDetail: "100% Cotton | 280gsm twill | Double chest pockets | Reinforced seams",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Khaki", "Navy", "Black"],
    weight: "380g",
    care: "Machine wash warm, iron medium",
    season: "SS26",
  },
  {
    id: "12",
    name: "Garment Dyed Sweat",
    category: "Sweatshirts",
    price: "Rp 5.600.000",
    image: "https://i.pinimg.com/1200x/91/3e/45/913e45de2a9a41d081f36ed8be722734.jpg",
    description: "A classic crewneck sweatshirt with a rich garment-dyed finish that gives each piece a unique tonal depth. Made from heavyweight cotton fleece with a brushed interior for exceptional comfort and warmth.",
    material: "Garment-dyed cotton fleece",
    materialDetail: "100% Cotton | 380gsm | Garment dyed | Brushed interior | Ribbed cuffs and hem",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Wine", "Forest Green", "Slate Blue"],
    weight: "580g",
    care: "Machine wash cold separately, do not bleach",
    season: "AW25",
  },
  {
    id: "13",
    name: "Field Jacket",
    category: "Jackets",
    price: "Rp 14.100.000",
    image: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTE3spr2irbdhfzrDDIvCz5HrMt5CDwCALaO70d3G_aKU3nKeYHyeO0ZY5_mGj6M1sFJ3Me3MjxmC31t-_Trfdk3H_LpgYAWNmKcEXZ0it6mpqz_UMpPeQ6G98",
    description: "A military-inspired field jacket built for the modern explorer. Features a durable ripstop shell, multiple utility pockets, adjustable waist drawstring, and a concealed hood. Designed to withstand the elements while maintaining a refined aesthetic.",
    material: "Military-grade ripstop cotton-nylon",
    materialDetail: "55% Cotton, 45% Nylon | Ripstop weave | Water repellent | 8 pockets | Concealed hood",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Military Green", "Black", "Desert"],
    weight: "780g",
    care: "Machine wash 30°C, do not dry clean",
    season: "AW25",
  },
  {
    id: "14",
    name: "Technical Cargo",
    category: "Trousers",
    price: "Rp 7.200.000",
    image: "https://i.pinimg.com/1200x/1b/7e/1e/1b7e1eccb34b56905b5ff9b9707aceca.jpg",
    description: "Advanced technical cargo trousers with a tapered fit and articulated construction. Made from a lightweight stretch fabric with water-repellent finish. Features cargo pockets with magnetic closures and adjustable ankle tabs.",
    material: "Stretch nylon with DWR finish",
    materialDetail: "88% Nylon, 12% Elastane | 4-way stretch | DWR finish | Magnetic cargo pockets",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Charcoal", "Olive"],
    weight: "380g",
    care: "Machine wash cold, do not iron decoration",
    season: "SS26",
  },
  {
    id: "15",
    name: "Compass Knit",
    category: "Knitwear",
    price: "Rp 6.800.000",
    image: "https://i.pinimg.com/1200x/ab/c0/87/abc087520a84b83f45318a6d0bc33fe7.jpg",
    description: "A premium knit sweater featuring the compass logo intarsia-knit into the chest. Made from extra-fine merino wool that is naturally temperature-regulating and odor-resistant. A refined piece for layering in cooler weather.",
    material: "Extra-fine merino wool",
    materialDetail: "100% Extra-fine Merino Wool | Intarsia knit | Ribbed trims | Naturally temperature regulating",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black/White", "Navy/Red"],
    weight: "420g",
    care: "Hand wash cold, lay flat to dry",
    season: "AW25",
  },
  {
    id: "16",
    name: "Nylon Down Jacket",
    category: "Outerwear",
    price: "Rp 16.500.000",
    image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcStP88IEn_4gDI_xrQxYrE1C_2QTYXGH63sf4jQ6a35-icZ19rhWJIadD1jKkuoUD93t59E0nQDuKN0dwgqH9I4OggeOfy_SxSNjEPo1vGMO4jbt8dw2-rkpw",
    description: "Premium down-filled jacket with a lightweight nylon shell treated with a water-resistant coating. Features quilted construction with high-loft goose down insulation for maximum warmth. Includes a detachable hood and storm cuffs.",
    material: "Water-resistant nylon with goose down insulation",
    materialDetail: "100% Nylon shell | 90/10 Goose down | 750 fill power | Water resistant | Detachable hood",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Blue", "Military Green"],
    weight: "720g",
    care: "Machine wash cold with down detergent, tumble dry low",
    season: "AW25",
  },
  {
    id: "17",
    name: "Compass Logo Cap",
    category: "Accessories",
    price: "Rp 2.850.000",
    image: "https://stoneisland-cdn.thron.com/delivery/public/image/stoneisland/L2S159100011S0076V0059_F/ppk73x/std/768x1024/9100011-nylon-metal-in-econylr,-photo.jpg?scalemode=centered&adjustcrop=reduce&quality=90&format=avif",
    description: "A structured cap featuring the iconic compass logo embroidered on the front panel. Made from durable cotton twill with an adjustable strap closure for a custom fit. A subtle yet recognizable accessory for everyday wear.",
    material: "Premium cotton twill",
    materialDetail: "100% Cotton twill | Embroidered logo | Adjustable strap | Structured crown",
    sizes: ["One Size"],
    colors: ["Black", "Navy", "White"],
    weight: "85g",
    care: "Spot clean only",
    season: "SS26",
  },
  {
    id: "18",
    name: "Compass Patch Beanie",
    category: "Accessories",
    price: "Rp 2.450.000",
    image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQHpVJN2JnnxJRSYV-6xNUIhE14mV2LaeKg31_ti7xo0bJeuGxr",
    description: "A ribbed knit beanie with the compass badge patch sewn onto the cuff. Made from a soft wool-acrylic blend that provides warmth without itching. The folded cuff design gives a classic silhouette with modern detailing.",
    material: "Wool-acrylic blend rib knit",
    materialDetail: "50% Wool, 50% Acrylic | Rib knit construction | Compass badge patch | Folded cuff",
    sizes: ["One Size"],
    colors: ["Black", "Grey", "Navy", "Burgundy"],
    weight: "65g",
    care: "Hand wash cold, lay flat to dry",
    season: "AW25",
  },
  {
    id: "19",
    name: "Technical Nylon Bag",
    category: "Accessories",
    price: "Rp 6.750.000",
    image: "https://stoneisland-cdn.thron.com/delivery/public/image/stoneisland/L1S159200015S0251V0024_F/ppk73x/std/768x1024/9200015-coated-nylon-metal-in-econylr,-photo.jpg?scalemode=centered&adjustcrop=reduce&quality=90&format=avif",
    description: "A technical crossbody bag crafted from coated nylon metal fabric with an iridescent finish. Features multiple compartments, adjustable strap, and water-resistant zippers. Compact yet functional for daily essentials.",
    material: "Coated nylon metal with iridescent finish",
    materialDetail: "100% Nylon | Coated finish | Water-resistant zippers | Adjustable strap | Multiple compartments",
    sizes: ["One Size"],
    colors: ["Graphite", "Black"],
    weight: "280g",
    care: "Wipe clean with damp cloth",
    season: "SS26",
  },
  {
    id: "20",
    name: "Logo Badge Wallet",
    category: "Accessories",
    price: "Rp 3.950.000",
    image: "https://stoneisland-cdn.thron.com/delivery/public/image/stoneisland/K2S159500007S0209V002B_F/ppk73x/std/768x1024/9500002-rubberised-silicone,-photo.jpg?scalemode=centered&adjustcrop=reduce&quality=90&format=avif",
    description: "A compact bifold wallet made from rubberised silicone with a tonal compass badge. Features multiple card slots, a note compartment, and a coin pocket with zip closure. Minimalist design meets functional craftsmanship.",
    material: "Rubberised silicone with tonal badge",
    materialDetail: "Rubberised silicone exterior | Leather lining | 8 card slots | Zip coin pocket | Note compartment",
    sizes: ["One Size"],
    colors: ["Black", "Dark Grey"],
    weight: "120g",
    care: "Wipe clean with damp cloth",
    season: "SS26",
  },
  {
    id: "21",
    name: "Compass Logo T-Shirt",
    category: "T-Shirts",
    price: "Rp 3.950.000",
    image: "https://images.voila.id/pr:sharp/rs:fit:1080:0/plain/https%3A%2F%2Fassets.voila.id%2Fvoila%2Fimages%2Fproduct%2Fstone-island%2F1product-81152NS81V0029-Xms-2024-12-05T1331360700.jpeg@webp",
    description: "A premium cotton t-shirt featuring the compass logo printed on the chest. Made from long-staple combed cotton for a smooth hand feel and excellent print retention. A wardrobe essential with iconic branding.",
    material: "Long-staple combed cotton",
    materialDetail: "100% Combed Cotton | 220gsm | Screen printed logo | Pre-shrunk | Reinforced neck",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Grey"],
    weight: "240g",
    care: "Machine wash cold, do not iron print",
    season: "SS26",
  },
  {
    id: "22",
    name: "Garment Dyed T-Shirt",
    category: "T-Shirts",
    price: "Rp 3.950.000",
    image: "https://eu.kith.com/cdn/shop/files/SI801523757-V0192-FRONT.jpg?v=1710924344&width=1920",
    description: "A heavyweight t-shirt with Stone Island's signature garment-dye process, creating rich tonal depth and a unique washed feel. Each piece has subtle color variations that make it one of a kind. Clean design with a small compass badge.",
    material: "Garment-dyed heavyweight cotton",
    materialDetail: "100% Cotton | 260gsm | Garment dyed | Each piece unique | Compass badge on sleeve",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Moss", "Clay", "Slate", "Ink"],
    weight: "280g",
    care: "Machine wash cold separately, colors may transfer",
    season: "SS26",
  },
  {
    id: "23",
    name: "Cotton Compass T-Shirt",
    category: "T-Shirts",
    price: "Rp 3.950.000",
    image: "https://stoneisland-cdn.thron.com/delivery/public/image/stoneisland/L2S152100026S0057V0189_F/ppk73x/std/768x1024/2100026-organic-cotton-jersey-fissato-effect,-photo.jpg?scalemode=centered&adjustcrop=reduce&quality=90&format=avif",
    description: "An organic cotton t-shirt with a fissato (torn) effect texture that adds visual depth. Features the compass logo in a tonal application. The organic cotton is grown without harmful pesticides, making it an eco-conscious choice.",
    material: "Organic cotton with fissato effect",
    materialDetail: "100% Organic Cotton | Fissato effect texture | Tonal compass logo | GOTS certified",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Off White", "Black", "Light Blue"],
    weight: "230g",
    care: "Machine wash cold, do not bleach",
    season: "SS26",
  },
];

export default productData;
