const productNames = {
  en: {
    "Soft Shell-R": "Soft Shell-R",
    "Nylon Metal Jacket": "Nylon Metal Jacket",
    "Ghost Piece Overshirt": "Ghost Piece Overshirt",
    "Compass Hoodie": "Compass Hoodie",
    "Cargo Pants": "Cargo Pants",
    "Technical Vest": "Technical Vest",
    "Organic Cotton Jersey": "Organic Cotton Jersey",
    "Garment Dyed Jacket": "Garment Dyed Jacket",
    "Technical Overshirt": "Technical Overshirt",
    "Lightweight Parka": "Lightweight Parka",
    "Utility Shirt": "Utility Shirt",
    "Garment Dyed Sweat": "Garment Dyed Sweat",
    "Field Jacket": "Field Jacket",
    "Technical Cargo": "Technical Cargo",
    "Compass Knit": "Compass Knit",
    "Nylon Down Jacket": "Nylon Down Jacket",
    "Compass Logo Cap": "Compass Logo Cap",
    "Compass Patch Beanie": "Compass Patch Beanie",
    "Technical Nylon Bag": "Technical Nylon Bag",
    "Logo Badge Wallet": "Logo Badge Wallet",
    "Compass Logo T-Shirt": "Compass Logo T-Shirt",
    "Garment Dyed T-Shirt": "Garment Dyed T-Shirt",
    "Cotton Compass T-Shirt": "Cotton Compass T-Shirt",
  },
  id: {
    "Soft Shell-R": "Jaket Soft Shell-R",
    "Nylon Metal Jacket": "Jaket Nylon Metal",
    "Ghost Piece Overshirt": "Overshirt Ghost Piece",
    "Compass Hoodie": "Hoodie Compass",
    "Cargo Pants": "Celana Cargo",
    "Technical Vest": "Vest Teknis",
    "Organic Cotton Jersey": "Jersey Katun Organik",
    "Garment Dyed Jacket": "Jaket Garment Dyed",
    "Technical Overshirt": "Overshirt Teknis",
    "Lightweight Parka": "Parka Ringan",
    "Utility Shirt": "Kemeja Utilitas",
    "Garment Dyed Sweat": "Sweat Garment Dyed",
    "Field Jacket": "Jaket Lapangan",
    "Technical Cargo": "Cargo Teknis",
    "Compass Knit": "Compass Knit",
    "Nylon Down Jacket": "Jaket Down Nylon",
    "Compass Logo Cap": "Topi Logo Compass",
    "Compass Patch Beanie": "Beanie Patch Compass",
    "Technical Nylon Bag": "Tas Nylon Teknis",
    "Logo Badge Wallet": "Dompet Badge Logo",
    "Compass Logo T-Shirt": "Kaos Logo Compass",
    "Garment Dyed T-Shirt": "Kaos Garment Dyed",
    "Cotton Compass T-Shirt": "Kaos Katun Compass",
  },
};

export default productNames;
